name: Test checkouts

on:
  push:
    branches-ignore:
      - 'release*'
      - gh-pages

jobs:
  comev2:
    name: Checkout with V2 - me
    runs-on: ubuntu-latest
    
    steps:
      - name: Check where we are
        run: |
          set -x
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR

      - uses: actions/checkout@v2

      - name: Check after checkout
        run: |
          set -x
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo And above
          ls -l ..

  coyouv2:
    name: Checkout with V2 - you
    runs-on: ubuntu-latest
    
    steps:
      - name: Check where we are
        run: |
          set -x
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR

      - uses: actions/checkout@v2
        with:
          repository: gitblit/gitblit-docker
          ref: master
          fetch-depth: 2

      - name: Check after checkout
        run: |
          set -x
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo And above
          ls -l ..

  comev3:
    name: Checkout with V3 - me
    runs-on: ubuntu-latest
    
    steps:
      - name: Check where we are
        run: |
          set -x
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR

      - uses: actions/checkout@v3

      - name: Check after checkout
        run: |
          set -x
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo And above
          ls -l ..

  coyouv3:
    name: Checkout with V3 - you
    runs-on: ubuntu-latest
    
    steps:
      - name: Check where we are
        run: |
          set -x
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR

      - uses: actions/checkout@v3
        with:
          repository: gitblit/gitblit-docker
          ref: master
          fetch-depth: 2

      - name: Check after checkout
        run: |
          set -x
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo And above
          ls -l ..

