name: Continous build - build and test on every push

on:
  push:
    branches-ignore:
      - 'release*'
      - gh-pages

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [7, 8, 11]
    
    steps:
      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Report Java version
        run: |
          java -version
          javac -version

      - name: Build with Ant
        run: |
          if ant -version 2> /dev/null ; then echo works ; else echo breaks ; fi
          ant -version && echo works || echo breaks
