name: Test checkouts

on:
  push:
    branches-ignore:
      - 'release*'
      - gh-pages

jobs:
  comev1:
    name: Checkout with V1 - me
    runs-on: ubuntu-latest
    
    steps:
      - name: Check where we are
        run: |
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo "Go up"
          cd ..
          pwd
          ls -lR

      - uses: actions/checkout@v1

      - name: Check after checkout
        run: |
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo Go up
          cd ..
          pwd
          ls -l

      - name: Check the checkout
        run: |
          pwd
          git status
          git branch -a -vv

  coyouv1:
    name: Checkout with V1 - you
    runs-on: ubuntu-latest
    
    steps:
      - name: Check where we are
        run: |
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo "Go up"
          cd ..
          pwd
          ls -lR

      - uses: actions/checkout@v1
        with:
          repository: gitblit/gitblit-docker
          ref: master
          fetch-depth: 2

      - name: Check after checkout
        run: |
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo Go up
          cd ..
          pwd
          ls -l

      - name: Check the checkout
        working-directory: ../gitblit-docker
        run: |
          pwd
          git status
          git branch -a -vv

  comev3:
    name: Checkout with V3 - me
    runs-on: ubuntu-latest
    
    steps:
      - name: Check where we are
        run: |
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo "Go up"
          cd ..
          pwd
          ls -lR

      - uses: actions/checkout@v3

      - name: Check after checkout
        run: |
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo Go up
          cd ..
          pwd
          ls -l

      - name: Check the checkout
        run: |
          pwd
          git status
          git branch -a -vv

  coyouv3:
    name: Checkout with V3 - you
    runs-on: ubuntu-latest
    
    steps:
      - name: Check where we are
        run: |
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo "Go up"
          cd ..
          pwd
          ls -lR

      - uses: actions/checkout@v3
        with:
          repository: gitblit/gitblit-docker
          ref: master
          fetch-depth: 2

      - name: Check after checkout
        run: |
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          pwd
          ls -lR
          echo Go up
          cd ..
          pwd
          ls -l

      - name: Check the checkout
        run: |
          pwd
          git status
          git branch -a -vv

