name: Perform release

on:
  pull_request:
    types:
      - edited
      - closed
      - ready_for_review
    branches:
      - 'release-builder'
      - release
      - master
  pull_request_review:
    types:
      - submitted
    branches:
      - release
      - release-builder
  release:
    types: [published]
  issue_comment:

jobs:
  info:
    name: Get event info
    runs-on: ubuntu-latest

    steps:
      - name: Get event environment
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_RFE: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"

      - name: Dump event payload
        env:
          GITHUB_CONTEXT_EVENT: ${{ toJSON(github.event) }}
        run: |
          echo "Action event name: ${{ github.event_name }}"
          echo "$GITHUB_CONTEXT_EVENT"

      - name: Checkout my repo
        uses: actions/checkout@v2
        with:
          ref: release

      - name: Match PR and parse version increase info
        if: ${{ 'pull_request_review' == github.event_name }}
        run: |
          echo "PR review for ${{ github.event.pull_request.title }}"
          if [ "$github.event.review.state" != approved ] ; then
            echo "PR review did not approve. (${{github.event.review.state}})"
            echo "Finishing here."
            exit 0
          fi
          echo "Parsing for instructions on increasing version."
          comment=$(gh pr view -c -c --json comments --jq '.comments[] | "\(.createdAt)\t\(.body)"' | sort | cut -f2 | grep "version" | tail -n1)
          revbody="${{ github.event.review.body }}"
          if [ -n "$revbody" ] ; then
            if echo "$revbody" | grep version >/dev/null ; then
              incver=$(echo "$revbody" | sed -e 's/.* [Ii]ncrease \(minor|patch\) version.*/\1/')
            fi
          fi
          if [ -z "$incver" ] ; then
            echo "Found no version instructions in review body."
            if echo "$comment" | grep version >/dev/null ; then
              incver=$(echo "$comment" | sed -e 's/.* [Ii]ncrease \(minor|patch\) version.*/\1/')
            fi
          fi
          if [ -n "$incver" ] ; then
            echo "Found version increment instruction: >$incver<"
            if [ "$incver" == minor -o "$invcer" == patch ] ; then
              echo "$incver" >> "$GITHUB_ENV"
            else
              echo "No viable version increment instruction found. Using default: patch"
              echo "patch" >> "$GITHUB_ENV"
            fi
          fi

